name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Instalar Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.x
        
    # Instalar as dependências NPM/Yarn;
    - name: Install dependencies 
      run: yarn
    
    # Executar a build    
    - name: Run build
      run: yarn build
    
    # Copiar a arquivos para dentro da Digital Ocean;
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ".,!node_modules"
        target: "~/app/go-barber-backend"
    
    # Instalar dependencias na Digital Ocean
    - name: Install dependencies on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/app/go-barber-backend
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-api
